# cloudbuild.yaml
steps:
  # Build & push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/CapstoneProject/capstone/ml-model:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/CapstoneProject/capstone/ml-model:$SHORT_SHA'

  # Submit Vertex AI custom training job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud ai custom-jobs create \
          --region=us-central1 \
          --display-name=capstone-train-$SHORT_SHA \
          --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,container-image-uri=us-central1-docker.pkg.dev/CapstoneProject/capstone/ml-model:$SHORT_SHA

images:
  - 'us-central1-docker.pkg.dev/CapstoneProject/capstone/ml-model:$SHORT_SHA'

steps:
  - name: 'us-central1-docker.pkg.dev/capstoneproject-462618/capstone/ml-model:latest'
    entrypoint: 'python'
    args: ['train.py']

options:
  logging: CLOUD_LOGGING_ONLY
