FROM python:3.9-slim

WORKDIR /app

# 1) Install TF native dependencies
RUN apt-get update && apt-get install -y \
      libgomp1 \
      libatlas3-base \
      libopenblas-dev \
    && rm -rf /var/lib/apt/lists/*

# 2) Copy & install Python deps
COPY requirements.txt .
RUN python -m pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# 3) Copy your serve code
COPY src/ ./src

EXPOSE 8080

ENTRYPOINT ["python", "src/serve.py"]
