FROM python:3.9-slim
WORKDIR /app

RUN apt-get update && apt-get install -y libgomp1 libatlas3-base libopenblas-dev \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN python -m pip install --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

COPY src-reg/ ./src-reg

EXPOSE 8080
ENTRYPOINT ["python", "src-reg/serve_reg.py"]
