FROM python:3.9-slim

WORKDIR /app

# Copy and upgrade pip first
COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src

EXPOSE 8080
ENTRYPOINT ["python", "src/serve.py"]
